#!/bin/bash
usage() {
    USAGE="Usage: Create opensaf node container\n
\t [-n] Name of container\n
\t [-H] Hostname of node\n
\t [-w] workspace of sharedfs\n
\t [-h] Usage
    "
    echo -e "$USAGE"
}

[ $# -eq 0 ] && usage && exit 0

while getopts ":n:H:w:h" OPT; do
    case $OPT in
        n) 
            NAME=$OPTARG
            ;;
        H)
            HOST=$OPTARG
            ;;
        w)
            WORKSPACE=$OPTARG
            ;;
        h)
            usage; exit 0
            ;;
        *)
            echo "Internal error"; exit 1
            ;;
    esac
done

if [ ! -d $WORKSPACE/sharedfs ]; then
    # Do not delete this folder, it just creates a node
    mkdir $WORKSPACE/sharedfs
    chmod -R 755 $WORKSPACE/sharedfs
fi
docker run -d --name $NAME -h $HOST --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $WORKSPACE/sharedfs:/etc/opensaf/sharedfs -it opensaf-cluster /sbin/init
