#!/bin/bash
#
# Create opensaf-cluster image which contains opensaf bin/lib and
# support scripts to start opensafd
#
# There're 2 ways of buidling opensaf:
# - On the host: Make install and then add the rootfs to the image
#   + 'make -j2; make -j2 install DESTDIR=$(pwd)/rootfs'
#   + Dockerfile: 'ADD rootfs /'
# - On the container: Compile and make install directly on the container
#    + Make volume of opensaf-repo: '-v /home/vudao/workspace/opensaf-code/:/home/opensaf'
#    + Compile code and 'make install'
#
# This script supports the first way
# TODO: The second one

WORKSPACE=$(readlink -e `dirname $0`)
DESTDIR="$WORKSPACE/rootfs"
REPO=$WORKSPACE/opensaf-code
IMAGENAME="opensaf-cluster"
flag="FALSE"
count=1

function set_up_workspace
{
    step "Setup workspace"
    rm -rf $DESTDIR
    rm -f $WORKSPACE/Dockerfile
    mkdir -p $DESTDIR
}

function step
{
    echo "Step ${count}: $@"
    count=$((count+1))
}

function clone_opensaf_repo
{
    if [ ! -d $REPO ]; then
        step "Clone opensaf repo"
        git clone -b develop git://git.code.sf.net/p/opensaf/code opensaf-code
    fi
}

function update_dockerfile {
    step "Update Dockerfile"
    cp $WORKSPACE/Dockerfile.temp $WORKSPACE/Dockerfile
}

function build_opensaf
{
    step "Build opensaf"
    cd $REPO 
    git clean -fxd
    ./bootstrap.sh
    ./configure CFLAGS="-DRUNASROOT -g -O2" --enable-imm-pbe --enable-python --disable-ais-evt \
    --disable-ais-lck --disable-ais-msg --enable-tests --disable-tipc
    make -j2
    make -j2 install DESTDIR=$DESTDIR
}

function usage {
USAGE="Create opensaf-cluster image\n
\t [-m | --make Build opensaf on the host\n
\t [-r | --repo opensaf repo\n
\t [-h | --help Print usage
    "
    echo -e "$USAGE"
}

function getoption {
    TEMP=`getopt -o r:mh --long repo:,notmake,help \
        -- "$@"`

    eval set -- $TEMP
    while true; do
        case "$1" in
            -m | --make) flag=TRUE; shift 1;;
            -r | --repo) REPO=$2; shift 2;;
            -h | --help) usage; exit 0;;
            --) shift; break;;
            *) echo "Internal error"; exit 1;;
        esac
    done
}

main() {
        getoption $@
        set_up_workspace
        if [ "$flag" == "TRUE" ]; then
            clone_opensaf_repo
            build_opensaf
        fi
        update_dockerfile
        step "Build image $IMAGENAME"
        cd $WORKSPACE; docker build --rm -t $IMAGENAME --network host -f Dockerfile .
}

main $@
