#!/bin/sh
# Overwritten opensaf-code/scripts/opensaf_scale_out to customize scale-out script
# Open source: https://sourceforge.net/projects/opensaf/

. /etc/opensaf/osafdir.conf

export PATH=$sbindir:$bindir:$PATH
export LD_LIBRARY_PATH=$libdir:$LD_LIBRARY_PATH

# NOTE 1: This script is a customization point between OpenSAF and a target
# system and should be changed according to the needs of such system.

# NOTE 2: The script must be idempotent, i.e. it must be harmless to call it
# more than one time with the same parameters. The second call should do nothing
# since the nodes were added to the cluster the first time the script was
# called.

# NOTE 3: This example script requires write access to the $pkgimmxmldir
# directory

if [ -f /usr/local/lib/opensaf/scale-out-opensaf.py ]; then
    for node_info in $@; do
        logger -t opensaf_scale_out "$node_info"
        hostname=$(echo $node_info | awk -F',' 'BEGIN{RS="^$"} {print $2}')
        python /usr/local/lib/opensaf/scale-out-opensaf.py --hostname $hostname --copy-from PL-3 | tee /var/log/opensaf_scale_out.log
    done
fi

# unlock-in/unlock the node
amf_node_name="safAmfNode=$hostname,safAmfCluster=myAmfCluster"
amf-adm unlock-in $amf_node_name
amf-adm unlock $amf_node_name

exit 0

# Env variable CLM_IFS contains field separator for the
# input argument, for example:
# save_ifs=$IFS
# for node in "$@"
#  do
#     logger "> [$node]"
#     IFS=$CLM_IFS
#     for arg in $node
#      do
#        logger ">> $arg"
#      done
#     IFS=$save_ifs
# done
